(define (same-parity signal . test)
  (define (even-fetch items)
    (if (null? items)
	'()
	(let ((first (car items)))
	  (if (even? first)
	      (cons first (even-fetch (cdr items)))
	      (even-fetch (cdr items))))))
  (define (odd-fetch items)
    (if (null? items)
	'()
	(let ((first (car items)))
	  (if (odd? first)
	      (cons first (odd-fetch (cdr items)))
	      (odd-fetch (cdr items))))))
  (if (even? signal)
      (cons signal (even-fetch test))
      (cons signal (odd-fetch test))))
      
