(define (same-parity signal . test)
  (define (fetch items p)
    (if (null? items)
	items
	(let ((first (car items)))
	  (if (p first)
	      (cons first (fetch (cdr items) p))
	      (fetch (cdr items) p)))))
    (if (even? signal)
      (cons signal (fetch test even?))
      (cons signal (fetch test odd?))))      
