(define (queen-8)
  (let ((first (amb 0 1 2 3 4 5 6 7)))
    (let ((second (amb 0 1 2 3 4 5 6 7)))
      (require (and (not (= first second)) (not (= (abs (- first second)) 1))))
      (let ((third (amb 0 1 2 3 4 5 6 7)))
	(require (and (not (= second third)) (not (= (abs (- second third)) 1))))
	(let ((fourth (amb 0 1 2 3 4 5 6 7)))
	  (require (and (not (= third fourth)) (not (= (abs (- third fourth)) 1))))
	  (let ((fifth (amb 0 1 2 3 4 5 6 7)))
	    (require (and (not (= fourth fifth)) (not (= (abs (- fourth fifth)) 1))))
	    (let ((sixth (amb 0 1 2 3 4 5 6 7)))
	      (require (and (not (= fifth sixth)) (not (= (abs (- fifth sixth)) 1))))
	      (let ((seventh (amb 0 1 2 3 4 5 6 7)))
		(require (and (not (= sixth seventh)) (not (= (abs (-sixth seventh)) 1))))
		(let ((eighth (amb 0 1 2 3 4 5 6 7)))
		  (require (and (not (= seventh eighth)) (not (= (abs (- seventh eighth)) 1))))
		  (list first second third fourth fifth sixth seventh eighth))))))))))
	
