(define (make-account balance password)
  (define (call-the-cops)
    (display "Cops on the way..."))
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((failure-entries 0))
    (define (dispatch p m)
      (if (eq? p password)
	  (begin (set! failure-entries 0)
		 (cond ((eq? m 'withdraw) withdraw)
		       ((eq? m 'deposit) deposit)
		       (else (error "Unknown request -- MAKE-ACCOUNT"
				    m))))
	  (begin (set! failure-entries (+ 1 failure-entries))
		 (if (< failure-entries 7)
		     (error "Incorrect password")
		     (call-the-cops)))))
    dispatch))
