(define (make-account balance pass)
  (let ((password (list pass)))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (begin (set! balance (+ balance amount))
	     balance))
    (define (joint new-password)
      (begin (set! password (cons new-password password))
	     dispatch))
    (define (dispatch p m)
      (if (memq p password)
	  (cond ((eq? m 'withdraw) withdraw)
		((eq? m 'deposit) deposit)
		((eq? m 'joint) joint)
		(else (error "Unknown request -- MAKE-ACCOUNT"
			     m)))
	  (error "Incorrect password")))
    dispatch))

(define (make-joint  acc old-pass new-pass)
  ((acc old-pass 'joint) new-pass))
