(define (rank)
  (let ((betty (amb 1 2 3 4 5))
	(a (amb 1 2 3 4 5))
	(joan (amb 1 2 3 4 5))
	(katty (amb 1 2 3 4 5))
	(mary (amb 1 2 3 4 5)))
    (require (or (and (= katty 2) (not (= betty 3))) (and (not (= katty 2)) (= betty 3))))
    (require (or (and (= a 1) (not (= joan 2))) (and (not (= a 1)) (= joan 2))))
    (require (or (and (= joan 3) (not (= a 5))) (and (not (= joan 3)) (= a 5))))
    (require (or (and (= katty 2) (not (= mary 4))) (and (not (= katty 2)) (= mary 4))))
    (require (or (and (= mary 4) (not (= betty 1))) (and (not (= mary 4)) (= betty 1))))
    (require (distinct? (list betty a joan katty mary)))
    (list (list 'betty betty)
	  (list 'a a)
	  (list 'joan joan)
	  (list 'katty katty)
	  (list 'mary mary))))
