(define (daugther-father)
  (define (sailor exp)
    (car exp))
  (define (father exp)
    (cadr exp))
  (define (name exp)
    (caddr exp))
  (let ((mary (list 'parker (amb 'moore) 'mary)))
    (let ((melissa (list 'downing (amb 'barnacle) 'melissa)))
      (let ((garbrielle (list 'barnacle (amb 'downing 'hall 'parker) 'garbrielle))
	    (rosalind (list 'hall (amb 'downing 'hall 'parker) 'rosalind))
	    (lorna (list 'moore (amb 'downing 'hall 'parker) 'lorna)))
	(require (not (eq? (father garbrielle) 'parker)))
	(require (not (eq? (father rosalind) 'hall)))
	(require (distinct? (map (lambda (i) (father (i)))
				 (list mary melissa garbrielle rosalind lorna))))
	(require (eq? (father
		       (car (filter (lambda (i) (= (father garbrielle) (sailor i)))
				    (list mary melissa garbrielle rosalind lorna))))
		      'parker))
	(father lorna)))))
